version: 1.0
name: AlphaCore
main: de.ops.alphacore.main.Main


commands:
  gm:
  heal:
  webpw:
  login:
  ban:
  tempban:
  check:
  unban:
  setrank:
  seerank:
  setspawn:
  spawn:
  money:
  setmoney:
  language:
  arl:
authors: [Justin, linksKeineMitte/Leonhard, Zeanon ]

loadbefore: [WorldSystem]
